apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library-management
  template:
    metadata:
      labels:
        app: library-management
    spec:
      containers:
        - name: library-management
          image: orkhan710/library-management:latest
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/librarymanagementsystem"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "orkhan"
          ports:
            - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: library-management
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9090        # Service-in açıq olacaq portu
      targetPort: 9090  # Pod içində işləyən tətbiqin portu
  selector:
    app: library-management
